apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
      - image: todo-server:1.0
        name: todo-server
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: server-side-configs
        - secretRef:
            name: server-side-secrets